#!/usr/bin/env bash

# Check if the number of arguments is less than 3
if [ $# -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign the provided arguments to variables
file_path=$1
server_ip=$2
username=$3
ssh_key=$4

# If the path to SSH key is not provided, use the default SSH key location
if [ -z "$ssh_key" ]; then
    ssh_key="$HOME/.ssh/id_rsa"
fi

scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip":~/

