#!/usr/bin/env bash
#script that configures a web server

sudo apt-get update
sudo apt install nginx

echo "Hello World" | sudo tee /var/www/html/index.html > /dev/null

config="
server {
listen 80;
listen [::]:80;

root /var/www/html;
index index.html index.htm index.nginx-debian.html;

server_name _;
add_header X-Served-By \$hostname;

location /{
try_files \$uri \$uri/ =404;
}
}"

echo "$config" | sudo tee /etc/nginx/sites-available/default  > /dev/null

sudo service nginx restart

