#!/usr/bin/env bash
#script to install haproxy in a server

sudo apt-get update -y
sudo apt install haproxy

config="
frontend ameliac.tech
        bind *:80
        default_backend web_backend

backend web_backend
        balance roundrobin
        server 325710-web-01 54.237.67.138:80 check
        server 325710-web-02 100.25.4.226:80 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy restart
